site_name: stzcpp
dev_addr: '127.0.0.1:5555'

docs_dir: docs
site_dir: site

theme:
  name: material

nav:

  - Home : 'index.md'

  - Roadmap      : 'roadmap.md'
  - Dependencies : 'deps.md'
  - Build system : 'build.md'

  - Genres summary : 'genres.md'

  - Genres details:
    - 1. Introduction                              : 'genres/01-intro.md'
    - 2. Built-in Functions                        : 'genres/02-builtin-functions.md'
    - 3. Built-in Constants                        : 'genres/03-builtin-constants.md'
    - 4. Built-in Types                            : 'genres/04-builtin-types.md'
    - 5. Built-in Exceptions                       : 'genres/05-builtin-exceptions.md'
    - 6. Text Processing Services                  : 'genres/06-text-processing-services.md'
    - 7. Binary Data Services                      : 'genres/07-binary-data-services.md'
    - 8. Data Types                                : 'genres/08-data-types.md'
    - 9. Numeric and Mathematical Modules          : 'genres/09-math.md'
    - 10. Functional Programming Modules           : 'genres/10-functional-programming.md'
    - 11. File and Directory Access                : 'genres/11-files-and-directory-access.md'
    - 12. Data Persistence                         : 'genres/12-data-peristence.md'
    - 13. Data Compression and Archiving           : 'genres/13-data-compression.md'
    - 14. File Formats                             : 'genres/14-file-formats.md'
    - 15. Cryptographic Services                   : 'genres/15-cryptographic-services.md'
    - 16. Generic Operating System Services        : 'genres/16-generic-operating-system-services.md'
    - 17. Command Line Interface Libraries         : 'genres/17-command-line-interface-libraries.md'
    - 18. Concurrent Execution                     : 'genres/18-concurrent-execution.md'
    - 19. Networking and Interprocess Communication: 'genres/19-networking-and-interprocess-communication.md'
    - 20. Internet Data Handling                   : 'genres/20-internet-data-handling.md'
    - 21. Structured Markup Processing Tools       : 'genres/21-structured-markup-processing-tools.md'
    - 22. Internet Protocols and Support           : 'genres/22-internet-protocols-and-support.md'
    - 23. Multimedia Services                      : 'genres/23-multimedia-services.md'
    - 24. Internationalization                     : 'genres/24-internationalization.md'
    - 25. Program Frameworks                       : 'genres/25-program-frameworks.md'
    - 26. Graphical User Interfaces with Tk        : 'genres/26-graphical-user-interfaces.md'
    - 27. Development Tools                        : 'genres/27-development-tools.md'
    - 28. Debugging and Profiling                  : 'genres/28-debugging-and-profiling.md'
    - 29. Software Packaging and Distribution      : 'genres/29-software-packaging-and-distribution.md'
    - 30. Runtime Services                         : 'genres/30-runtime-services.md'
    - 31. Custom Interpreters                      : 'genres/31-custom-interpreters.md'
    - 32. Importing Modules                        : 'genres/32-importing-modules.md'
    - 33. Language Services                        : 'genres/33-language-services.md'
    - 34. MS Windows Specific Services             : 'genres/34-windows-specific-services.md'
    - 35. Unix Specific Services                   : 'genres/35-unix-specific-services.md'
    - 36. Modules command-line interface (CLI)     : 'genres/36-modules-cli.md'
    - 37. Superseded Modules                       : 'genres/37-superseded-modules.md'
    - 38. Removed Modules                          : 'genres/38-removed-modules.md'
    - 39. Security Considerations                  : 'genres/39-security-considerations.md'

  - Prior-art:
    - Standard libraries:
      - C         : 'prior-art/std-c.md'
      - C++       : 'prior-art/std-cpp.md'
      - Zig       : 'prior-art/std-zig.md'
      - Rust      : 'prior-art/std-rust.md'
      - Go        : 'prior-art/std-go.md'
      - Python    : 'prior-art/std-python.md'
      - Javascript: 'prior-art/std-js.md'

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

plugins:
  - search
  - mermaid2
  - table-reader
